name: Java CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - run: sudo /usr/bin/mvn clean compile

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - run: echo "random garbage"

      - run: echo ${{secrets.SSHPASSWORD}} | ssh -S ${{secrets.SSHUSERNAME}}@${{secrets.SSHHOST}} "echo 0000 | sudo -S systemctl restart raspi.service"
